apiVersion: v1
kind: ServiceAccount
metadata:
  name: disclaude-bot
  namespace: disclaude
  labels:
    app: disclaude-bot
    component: disclaude

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: disclaude-bot
  namespace: disclaude
  labels:
    app: disclaude-bot
    component: disclaude
rules:
# Podの管理権限
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Pod execの実行権限
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

# Pod logsの読み取り権限
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

# ConfigMapの読み取り権限
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# Secretの読み取り権限
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

# Eventの読み取り権限（デバッグ用）
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: disclaude-bot
  namespace: disclaude
  labels:
    app: disclaude-bot
    component: disclaude
subjects:
- kind: ServiceAccount
  name: disclaude-bot
  namespace: disclaude
roleRef:
  kind: Role
  name: disclaude-bot
  apiGroup: rbac.authorization.k8s.io

---
# Namespace管理用のClusterRole（オプション）
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disclaude-namespace-manager
  labels:
    app: disclaude-bot
    component: disclaude
rules:
# Namespaceの管理権限
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  resourceNames: ["disclaude"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: disclaude-namespace-manager
  labels:
    app: disclaude-bot
    component: disclaude
subjects:
- kind: ServiceAccount
  name: disclaude-bot
  namespace: disclaude
roleRef:
  kind: ClusterRole
  name: disclaude-namespace-manager
  apiGroup: rbac.authorization.k8s.io