apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-claude-bot
  namespace: discord-claude
spec:
  replicas: 1  # Discord Botは通常1つのレプリカで十分

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: discord-claude
spec:
  replicas: 1  # PostgreSQLは単一インスタンス（ReadWriteOnceのため）