apiVersion: apps/v1
kind: Deployment
metadata:
  name: disclaude-bot
  namespace: disclaude
spec:
  replicas: 1  # Discord Botは通常1つのレプリカで十分

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: disclaude
spec:
  replicas: 1  # PostgreSQLは単一インスタンス（ReadWriteOnceのため）