apiVersion: v1
kind: Secret
metadata:
  name: disclaude-secrets
  namespace: disclaude
  labels:
    app: disclaude
    component: disclaude
type: Opaque
data:
  # NOTE: これらの値は base64 エンコードされている必要があります
  # 実際の値を設定する前に base64 エンコードしてください
  # 例: echo -n "your-token-here" | base64
  
  discord-token: ""          # Discord Bot Token (base64 encoded)
  db-password: ""            # PostgreSQL Password (base64 encoded)
  claude-api-key: ""         # Claude API Key (base64 encoded)

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-secrets
  namespace: disclaude
  labels:
    app: claude-sandbox
    component: disclaude
type: Opaque
data:
  # Claude Code サンドボックス用のシークレット
  api-key: ""               # Claude API Key (base64 encoded) - Same as above

---
# Kubernetesクラスタ外で実行する場合のkubeconfig
# クラスタ内で実行する場合は不要
apiVersion: v1
kind: Secret
metadata:
  name: disclaude-kubeconfig
  namespace: disclaude
  labels:
    app: disclaude-bot
    component: disclaude
type: Opaque
data:
  config: ""                # kubeconfig file content (base64 encoded)
                           # クラスタ内実行時は空でOK