apiVersion: v1
kind: Service
metadata:
  name: disclaude-bot
  namespace: disclaude
  labels:
    app: disclaude-bot
    component: disclaude
spec:
  selector:
    app: disclaude-bot
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP